[package]
name = "graph"
version = "0.1.0"
edition = "2024"
description = "Core of the database"
license = "MIT"
repository = "https://github.com/FalkorDB/falkordb-rs"
readme = "../README.md"
keywords = ["graph", "database"]
categories = ["data-structures", "database"]

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin)'] }


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
falkordb-macro = { path = "../falkordb-macro" }
once_cell = "1.21.3"
ordermap = "0.5.7"
orx-tree = "1.7.1"
rand = "0.9.1"
regex = "1.11.1"
roaring = "0.11.0"
tracing = "0.1"
unescaper = "0.1.6"
