name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: aviavni/falkordb-build:latest
          context: ./build
  test:
    runs-on: ubuntu-latest
    container: aviavni/falkordb-build:latest
    needs: docker
    steps:
      - uses: actions/checkout@v3
      - name: Format
        run: |
          rustup default stable
          cargo fmt --all --check
      - name: Lint
        run: |
          cargo clippy --all --all-targets
      - name: Build
        run: |
          cargo build
      - name: Run unit tests
        run: |
          cargo test -p graph
      - name: Run tests
        run: |
          . /data/venv/bin/activate
          pytest tests/test_e2e.py
  coverage:
    runs-on: ubuntu-latest
    container: aviavni/falkordb-build:latest
    needs: docker
    steps:
      - uses: actions/checkout@v3
      - name: Run code coverage
        run: |
          rustup default stable
          RUSTFLAGS="-C instrument-coverage" cargo build
          RUSTFLAGS="-C instrument-coverage" cargo test -p graph
          mkdir cov
          cd cov
          . /data/venv/bin/activate
          TARGET=../target/debug/libfalkordb.so pytest ../tests/test_e2e.py
          llvm-profdata-20 merge --sparse `find . -name "*.profraw"` -o cov.profdata
          llvm-cov-20 export --format=lcov --instr-profile cov.profdata ../target/debug/libfalkordb.so > codecov.txt.all
          lcov --ignore-errors unused -r codecov.txt.all -o codecov.txt
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  falkordb-e2e-compatibility:
    runs-on: ubuntu-latest
    services:
      falkordb:
        image: falkordb/falkordb:edge
        ports:
          - 6379:6379
        volumes:
          - ./data:/var/lib/falkordb/data
        options: >-
          --rm
          -it
    steps:
      - uses: actions/checkout@v3

      - name: Wait for FalkorDB to be ready
        run: |
          # Wait until port 6379 is open (max 30 seconds)
          for i in {1..30}; do
            if nc -z localhost 6379; then
              echo "FalkorDB is up!"
              break
            fi
            echo "Waiting for FalkorDB..."
            sleep 1
          done

      - name: Run FalkorDB e2e tests
        run: |
          . /data/venv/bin/activate
          pytest tests/test_falkordb_e2e.py
