name: Rust PR Closed

permissions:
  contents: read

on:
    pull_request:
      branches: ["main"]
      types: [closed]

jobs:
  delete-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Delete Docker image tag
        run: |
          curl -X DELETE -H "Authorization: Bearer ${{ secrets.DOCKERHUB_TOKEN }}" \
            "https://hub.docker.com/v2/repositories/aviavni/falkordb-build/tags/${{ github.event.pull_request.number }}"